apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydep
  template:
    metadata:
      labels:
        app: mydep
    spec:
      containers:
      - name: con1
        image: wordpress:latest
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: wpcm
              key: WORDPRESS_DB_HOST
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_PASSWORD
          value: test123
        - name: WORDPRESS_DB_NAME
          value: mydb
        - name: WORDPRESS_TABLE_PREFIX
          value: wp_
   
---
apiVersion: v1
kind: Service
metadata:
  name: mydep-svc
spec:
  selector:
    app: mydep
  ports:
  - port: 80
    targetPort: 80

