apiVersion: v1
kind: LimitRange
metadata:
  name: devops-lr
  namespace: devops
spec:
  limits:
  - default: # this section defines default limits
      cpu: "200m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "64Mi"
    type: Container
