apiVersion: v1
kind: Pod
metadata:
   name: testpod
   namespace: devops
   labels:
      app: myapp
spec:
   serviceAccountName: robo
   containers:
   - name: con1 
     image: nginx:latest
     ports:
     - containerPort: 80
