apiVersion: v1
kind: ResourceQuota
metadata:
  name: devops-rq
  namespace: devops
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "1Gi"
    limits.cpu: "2"
    limits.memory: "2Gi"
    configmaps: "10"
    persistentvolumeclaims: "4"
    pods: "10"
    replicationcontrollers: "20"
    secrets: "10"
    services: "10"
    services.loadbalancers: "2"
